trigger:
  branches:
    include:
    - matrix-build


jobs:
- job: windowsbuild
  displayName: Windows build on Python Image
  pool:
    name: local-windows
    


  steps:
  - powershell: |
      docker build -t agogosml_cli:latest-windows -f Dockerfile.windows .
    workingDirectory: ./agogosml_cli


    
      